// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Board struct {
	ID         uuid.UUID
	BoardTitle string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type List struct {
	ID        uuid.UUID
	BoardID   uuid.UUID
	ListTitle string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Task struct {
	ID          uuid.UUID
	ListID      uuid.UUID
	TaskTitle   string
	Description string
	DueDate     time.Time
	AssignedTo  string
	Status      string
	Labels      []string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
