// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: Tasks.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, list_id, task_title, description, due_date, assigned_to, status, labels, created_at, updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7, 
		$8,
		$9,
		$10
)
RETURNING id, list_id, task_title, description, due_date, assigned_to, status, labels, created_at, updated_at
`

type CreateTaskParams struct {
	ID          uuid.UUID
	ListID      uuid.UUID
	TaskTitle   string
	Description string
	DueDate     time.Time
	AssignedTo  string
	Status      string
	Labels      []string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ID,
		arg.ListID,
		arg.TaskTitle,
		arg.Description,
		arg.DueDate,
		arg.AssignedTo,
		arg.Status,
		pq.Array(arg.Labels),
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.TaskTitle,
		&i.Description,
		&i.DueDate,
		&i.AssignedTo,
		&i.Status,
		pq.Array(&i.Labels),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
